"""Добавил таблицу чекбоксов

Revision ID: 6b5f8d5df49b
Revises: ea055815ea0b
Create Date: 2021-04-08 16:50:07.340623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5f8d5df49b'
down_revision = 'ea055815ea0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkboxlist', sa.Column('checkbox_privacy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkboxlist', 'checkbox_privacy')
    # ### end Alembic commands ###
