"""Добавил таблицу чекбоксов

Revision ID: bab63bf914d0
Revises: 6b5f8d5df49b
Create Date: 2021-04-08 17:00:28.256572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab63bf914d0'
down_revision = '6b5f8d5df49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkbox', sa.Column('checkbox_status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkbox', 'checkbox_status')
    # ### end Alembic commands ###
