"""Добавил таблицу чекбоксов

Revision ID: ea055815ea0b
Revises: 478bd7fef078
Create Date: 2021-04-08 14:07:26.232931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea055815ea0b'
down_revision = '478bd7fef078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_user_name'), 'user', ['user_name'], unique=True)
    op.create_table('checkboxlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkbox_list_title', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkboxlist_checkbox_list_title'), 'checkboxlist', ['checkbox_list_title'], unique=False)
    op.create_table('checkbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkbox_name', sa.String(length=128), nullable=True),
    sa.Column('checkbox_list', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checkbox_list'], ['checkboxlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkbox_checkbox_name'), 'checkbox', ['checkbox_name'], unique=False)
    op.drop_index('ix_users_user_name', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_user_name', 'users', ['user_name'], unique=1)
    op.drop_index(op.f('ix_checkbox_checkbox_name'), table_name='checkbox')
    op.drop_table('checkbox')
    op.drop_index(op.f('ix_checkboxlist_checkbox_list_title'), table_name='checkboxlist')
    op.drop_table('checkboxlist')
    op.drop_index(op.f('ix_user_user_name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
